---
repository:
  name: terragrunt-labs
  description: A Collection of Terragrunt Labs, experiments, and tests
  topics: terragrunt, terraform, opentofu, infrastructure-as-code, devops, cloud
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  has_projects: true
  has_wiki: true

labels:
  - name: infra/terragrunt
    color: '#1D76DB'
    description: Terragrunt configuration and infrastructure changes
  - name: infra/terraform
    color: '#0075CA'
    description: Terraform module modifications
  - name: tool/gh-issue-puller
    color: '#7B42BC'
    description: GitHub Issue Puller CLI tool enhancements
  - name: performance
    color: '#FFC300'
    description: Performance optimization for infrastructure configurations
  - name: docs
    color: '#5319E7'
    description: Documentation changes
  - name: bug
    color: '#FF4136'
    description: Bug fixes
  - name: breaking
    color: '#FF4136'
    description: Breaking changes
  - name: feature
    color: '#3D9970'
    description: New features
  - name: maintenance
    color: '#0075CA'
    description: Maintenance changes
  - name: dx
    color: '#5319E7'
    description: DX (Developer Experience) improvements

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "lint"
          - "test"
          - "codecov/project"
      enforce_admins: false
      restrictions:
        apps: []
        teams: []
